name: Rust sec_store

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    working-directory: ./sec_store

    steps:
    - uses: actions/checkout@v3
    - name: Fetch dependencies
      run: cargo fetch --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run fmt check
      run: cargo fmt --check
    - name: Build
      run: cargo build --release --verbose